// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:linkify/_core/storage/hive_db.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LinkDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LinkDataAdapter());
  }
}
